"""The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?"""

from math import sqrt

max_factors = 0
nth_term = 0  # nth triangle number

while max_factors < 500:
    factors = 0

    triangle_number = int(nth_term * (nth_term+1)/2)

    # for i in range(nth_term):
    #     triangle_number += i
    # triangle_number = sum([i for i in range(nth_term)])

    for j in range(1, round(sqrt(triangle_number))):
        if not (triangle_number % j):
            factors += 2

    # print(factors, triangle_number, nth_term-1)

    if factors > max_factors:
        max_factors = factors

    nth_term += 1

else:
    print(f"{triangle_number} has {max_factors} factors")

# returns 76576500
