conj = " "

number_dictionary = {
    0:
        {0: "zero",
         1: "one",
         2: "two",
         3: "three",
         4: "four",
         5: "five",
         6: "six",
         7: "seven",
         8: "eight",
         9: "nine"},
    1:
        {2: "twenty",
         3: "thirty",
         4: "fourty",
         5: "fifty",
         6: "sixty",
         7: "seventy",
         8: "eighty",
         9: "ninety"},
    "exceptions":
        {0: "ten",
         1: "eleven",
         2: "twelve",
         3: "thirteen",
         4: "fourteen",
         5: "fifteen",
         6: "sixteen",
         7: "seventeen",
         8: "eighteen",
         9: "nineteen"}
}

modifiers = {
 3: "thousand",
 6: "million",
 9: "billion",
 12: "trillion",
 15: "quadrillion",
 18: "quintillion",
 21: "sextillion",
 24: "septillion",
 27: "octillion",
 30: "nonillion",
 33: "decillion",
 36: "undecillion",
 39: "duodecillion",
 42: "tredecillion",
 45: "quattuordecillion",
 48: "quindecillion",
 51: "sexdecillion",
 54: "septendecillion",
 57: "octodecillion",
 60: "novemdecillion",
 63: "vigintillion",
 66: "unvigintillion",
 69: "duovigintillion",
 72: "trevigintillion",
 75: "quattuorvigintillion",
 78: "quinvigintillion",
 81: "sexvigintillion",
 84: "septenvigintillion",
 87: "octovigintillion",
 90: "novemvigintillion",
 93: "trigintillion",
 96: "untrigintillion",
 99: "duotrigintillion"
}